version: '3'
services:
  server:
    image: rustlang/rust:nightly
    volumes:
      - ./server:/app
      - ./client:/app/static
    command: bash -c "cd /app && cargo run --release"
    ports:
      - "80:80"

volumes:
  client:
  server:
