[package]
name = "server"
version = "0.1.0"
authors = ["Wiktor Mazur <wiktormazur1@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
simplelog = "~0.5.0"
rocket = "0.4.0-rc.2"
rocket_contrib = " 0.4.0"
